name: molproplab
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - freetype-py=2.3.0
  - greenlet=3.2.4
  - icu=75.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.11.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.2
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libpng=1.6.51
  - libpq=18.1
  - librdkit=2025.09.3
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - matplotlib-base=3.10.8
  - mkl=2025.3.0
  - munkres=1.1.4
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pycairo=1.29.0
  - pyparsing=3.2.5
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - rdkit=2025.09.3
  - reportlab=4.4.5
  - rlpycairo=0.4.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=2.0.44
  - tbb=2022.3.0
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - certifi==2025.11.12
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - lightgbm==4.6.0
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - propcache==0.4.1
      - psutil==7.1.3
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shap==0.49.1
      - slicer==0.0.8
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torch-geometric==2.7.0
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
